server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
    druid:
      # 数据库访问配置, 使用druid数据源 
      db-type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/hep?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: 123456
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
      filters: stat
      # Spring监控AOP切入点，如 x.y.z.service.*,配置多个英文逗号分隔
      aop-patterns: cc.hep.*.service.*

      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,/actuator/*'

      # StatViewServlet配置 
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台
        login-username: admin
        login-password: 123456
        # IP白名单
        # allow: 127.0.0.1
        # IP黑名单（共同存在时，deny优先于allow）
        # deny: 192.168.1.218

      # 配置StatFilter
      filter:
        stat:
          log-slow-sql: true
  mail:
    host: smtp.163.com
    username: 15170091857@163.com
    password: a133918936890
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
            required: true


    smtp:
      socketFactory:
        port: 465
        class: javax.net.ssl.SSLSocketFactory
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password:
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒）
    timeout: 0
  thymeleaf:
    #cache: false
  aop:
    proxy-target-class: true
  cache:
    type:
      redis

mail:
  fromMail:
    sender: 15170091857@163.com
    receiver: 2679998262@qq.com

jasypt:
  encryptor:
    password: febs

mybatis:
  # type-aliases扫描路径
  type-aliases-package: cc.hep.system.domain
  # mapper xml实现扫描路径
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
    # 使用jdbc的getGeneratedKeys 可以获取数据库自增主键值
    use-generated-keys: true
    # 使用列别名替换列名，默认true。如：select name as title from table
    use-column-label: true
    # 开启驼峰命名转换，如：Table(create_time) -> Entity(createTime)。不需要我们关心怎么进行字段匹配，mybatis会自动识别`大写字母与下划线`
    map-underscore-to-camel-case: true

mapper:
  mappers: cc.hep.common.config.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# febs 配置
febs:
  # 是否在控制台打印 sql语句
  showsql: true
  # 时间类型参数在前端页面的展示格式，默认格式为 yyyy-MM-dd HH:mm:ss
  timeFormat: yyyy-MM-dd HH:mm:ss
  # 是否开启 AOP 日志，默认开启
  openAopLog: true
  shiro:
    # shiro redis缓存时长，默认1800秒
    expireIn: 1800
    # session 超时时间，默认1800000毫秒
    sessionTimeout: 1800000
    # rememberMe cookie有效时长，默认86400秒，即一天
    cookieTimeout: 86400
    # 免认证的路径配置，如静态资源，druid监控页面，注册页面，验证码请求等
    anonUrl: /css/**,/js/**,/fonts/**,/img/**,/druid/**,/user/regist,/gifCode,/,/actuator/**,/smsTest/**,/shortMessageCode/**,/mailMessageCode/**
    # 登录 url
    loginUrl: /login
    # 登录成功后跳转的 url
    successUrl: /index
    # 登出 url
    logoutUrl: /logout
    # 未授权跳转 url
    unauthorizedUrl: /403
  # 验证码
  validateCode:
    # 宽度，默认 146px
    width: 146
    # 高度，默认 33px
    height: 33
    # 验证码字符个数，默认4个字符
    length: 4


